apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r188ypcbq-nodejs
  janus-idp.io/tekton: r188ypcbq-nodejs
  backstage.io/kubernetes-id: r188ypcbq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r188ypcbq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
